version: 2
updates:
  - package-ecosystem: "uv"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      python-dependencies:
        patterns:
          - "*"
  
  - package-ecosystem: "github-actions"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ministryofjustice/hmpps-github-actions/*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "helm"
    directory: "/helm_deploy/hmpps-veracode-discovery"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "docker"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"
