[project]
name = "hmpps-veracode-discovery"
version = "0.1.5"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hmpps-sre-python-lib",
    "veracode-api-signing==26.5.0",
]

[tool.uv.sources]
hmpps-sre-python-lib = { git = "https://github.com/ministryofjustice/hmpps-sre-python-lib", branch = "feat/HEAT-1286" }
