---
generic-service:
  nameOverride: hmpps-veracode-discovery

  replicaCount: 1

  image:
    repository: ghcr.io/ministryofjustice/hmpps-veracode-discovery
    tag: xxx    # override at deployment time
    port: 8080

  ingress:
    enabled: false

  # Due to a bug cant disable/override the sub chart.
  # https://github.com/helm/helm/pull/12162
  # Have implemented a basic http health endpoint, until this bug is fixed.
  #livenessProbe: null
  #readinessProbe: null

  livenessProbe:
    httpGet:
      path: /ping
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5

  readinessProbe:
    httpGet:
      path: /ping
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5

  # Environment variables to load into the deployment
  env:
    REFRESH_INTERVAL: "7200"
    LOG_LEVEL: debug

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-veracode-discovery:
      SERVICE_CATALOGUE_API_ENDPOINT: "SERVICE_CATALOGUE_API_ENDPOINT"
      SERVICE_CATALOGUE_API_KEY: "SERVICE_CATALOGUE_API_KEY"
      VERACODE_API_KEY_ID: "VERACODE_API_KEY_ID"
      VERACODE_API_KEY_SECRET: "VERACODE_API_KEY_SECRET"

generic-prometheus-alerts:
  targetApplication: hmpps-veracode-discovery
